import RomeoAndJulet from "../assets/RomeoAndJulet.jpg"

export const MovieData = [
  {
    "id": 1,
    "title": "Inception",
    "year": 2010,
    "genre": ["Action", "Adventure", "Sci-Fi"],
    "rating": 8.8,
    "director": "Christopher Nolan",
    "actors": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    "plot": "A thief who enters the dreams of others to steal secrets is given a chance to have his past crimes forgiven.",
    "poster": "Inception",
    "trailer": "Inception",
    "runtime": 148,
    "awards": "Won 4 Oscars",
    "country": "USA",
    "language": "English",
    "boxOffice": "$836.8 million",
    "production": "Warner Bros.",
    "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/inception.jpg"
  },
  {
    "id": 2,
    "title": "The Dark Knight",
    "year": 2008,
    "genre": ["Action", "Crime", "Drama"],
    "rating": 9.0,
    "director": "Christopher Nolan",
    "actors": ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    "plot": "Batman faces the Joker, a criminal mastermind who seeks to create chaos in Gotham City.",
    "poster": "The_Dark_Knight",
    "trailer": "TheDarkKnight",
    "runtime": 152,
    "awards": "Won 2 Oscars",
    "country": "USA",
    "language": "English",
    "boxOffice": "$1.005 billion",
    "production": "Warner Bros.",
    "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/dark+knight+rises.jpg"
  },
  {
    "id": 3,
    "title": "Avatar",
    "year": 2009,
    "genre": ["Action", "Adventure", "Fantasy"],
    "rating": 7.8,
    "director": "James Cameron",
    "actors": ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
    "plot": "A paraplegic Marine is sent to Pandora and becomes part of the Na'vi culture.",
    "poster": "Avatar",
    "trailer": "Avatar",
    "runtime": 162,
    "awards": "Won 3 Oscars",
    "country": "USA",
    "language": "English",
    "boxOffice": "$2.923 billion",
    "production": "20th Century Fox",
    "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/avatar.jpg"
  },
  {
    "id": 4,
    "title": "Interstellar",
    "year": 2014,
    "genre": ["Adventure", "Drama", "Sci-Fi"],
    "rating": 8.7,
    "director": "Christopher Nolan",
    "actors": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    "plot": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    "poster": "Interstellar",
    "trailer": "Interstellar",
    "runtime": 169,
    "awards": "Won 1 Oscar",
    "country": "USA",
    "language": "English",
    "boxOffice": "$677.5 million",
    "production": "Paramount Pictures",
    "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/interstellar.jpg"
  },
  {
    "id": 5,
    "title": "The Godfather",
    "year": 1972,
    "genre": ["Crime", "Drama"],
    "rating": 9.2,
    "director": "Francis Ford Coppola",
    "actors": ["Marlon Brando", "Al Pacino", "James Caan"],
    "plot": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    "poster": "The_Godfather",
    "trailer": "TheGodfather",
    "runtime": 175,
    "awards": "Won 3 Oscars",
    "country": "USA",
    "language": "English",
    "boxOffice": "$245.1 million",
    "production": "Paramount Pictures",
    "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/The+Godfather.jpg"
  },
  {
    "id": 6,
    "title": "The Lord of the Rings",
    "year": 2001,
    "genre": ["Adventure", "Drama", "Fantasy"],
    "rating": 8.8,
    "director": "Peter Jackson",
    "actors": ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
    "plot": "A meek Hobbit and his companions set out on a journey to destroy the One Ring and save Middle-earth.",
    "poster": "The_Lord_of_the_Rings",
    "trailer": "TheLordoftheRings",
    "runtime": 178,
    "awards": "Won 4 Oscars",
    "country": "USA",
    "language": "English",
    "boxOffice": "$897.7 million",
    "production": "New Line Cinema",
    "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/The+Lord+of+the+Rings.jpg"
  },
  {
      "id": 7,
      "title": "The Matrix",
      "year": 1999,
      "genre": ["Action", "Sci-Fi"],
      "rating": 8.7,
      "director": "Lana Wachowski, Lilly Wachowski",
      "actors": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
      "plot": "A computer hacker learns about the true nature of reality and his role in the war against its controllers.",
      "poster": "The_Matrix",
      "trailer": "TheMatrix",
      "runtime": 136,
      "awards": "Won 4 Oscars",
      "country": "USA",
      "language": "English",
      "boxOffice": "$466.6 million",
      "production": "Warner Bros.",
      "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/The+Matrix.jpg"
    },
    {
      "id": 8,
      "title": "The Silence of the Lambs",
      "year": 1991,
      "genre": ["Crime", "Drama", "Thriller"],
      "rating": 8.6,
      "director": "Jonathan Demme",
      "actors": ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
      "plot": "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to catch another serial killer.",
      "poster": "The_Silence_of_the_Lambs",
      "trailer": "TheSilenceoftheLambs",
      "runtime": 118,
      "awards": "Won 5 Oscars",
      "country": "USA",
      "language": "English",
      "boxOffice": "$272.7 million",
      "production": "Orion Pictures",
      "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/The+Silence+of+the+Lambs.jpg"
    },
    {
      "id": 9,
      "title": "Fight Club",
      "year": 1999,
      "genre": ["Drama"],
      "rating": 8.8,
      "director": "David Fincher",
      "actors": ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
      "plot": "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much more.",
      "poster": "Fight_Club",
      "trailer": "FightClub",
      "runtime": 139,
      "awards": "Nominated for 1 Oscar",
      "country": "USA",
      "language": "English",
      "boxOffice": "$101.2 million",
      "production": "20th Century Fox",
      "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/Fight+Club.jpg"
    },
    {
      "id": 10,
      "title": "The Lion King",
      "year": 1994,
      "genre": ["Animation", "Adventure", "Drama"],
      "rating": 8.5,
      "director": "Roger Allers, Rob Minkoff",
      "actors": ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"],
      "plot": "Lion prince Simba flees his kingdom after the death of his father, only to return as an adult to reclaim it.",
      "poster": "The_Lion_King",
      "trailer": "TheLionKing",
      "runtime": 88,
      "awards": "Won 2 Oscars",
      "country": "USA",
      "language": "English",
      "boxOffice": "$968.5 million",
      "production": "Walt Disney Pictures",
      "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/The+Lion+King.jpg"
    },
    {
      "id": 11,
      "title": "Jurassic Park",
      "year": 1993,
      "genre": ["Adventure", "Sci-Fi", "Thriller"],
      "rating": 8.2,
      "director": "Steven Spielberg",
      "actors": ["Sam Neill", "Laura Dern", "Jeff Goldblum"],
      "plot": "During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok.",
      "poster": "Jurassic_Park",
      "trailer": "JurassicPark",
      "runtime": 127,
      "awards": "Won 3 Oscars",
      "country": "USA",
      "language": "English",
      "boxOffice": "$1.033 billion",
      "production": "Universal Pictures",
      "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/Jurassic+Park.jpg"
    },
    {
      "id": 12,
      "title": "The Avengers",
      "year": 2012,
      "genre": ["Action", "Adventure", "Sci-Fi"],
      "rating": 8.0,
      "director": "Joss Whedon",
      "actors": ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
      "plot": "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
      "poster": "The_Avengers",
      "trailer": "Avengers",
      "runtime": 143,
      "awards": "Nominated for 1 Oscar",
      "country": "USA",
      "language": "English",
      "boxOffice": "$1.519 billion",
      "production": "Marvel Studios",
      "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/The+Avengers.jpg"
    },
    {
      "id": 13,
      "title": "Titanic",
      "year": 1997,
      "genre": ["Drama", "Romance"],
      "rating": 7.9,
      "director": "James Cameron",
      "actors": ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"],
      "plot": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
      "poster": "Titanic",
      "trailer": "Titanic",
      "runtime": 195,
      "awards": "Won 11 Oscars",
      "country": "USA",
      "language": "English",
      "boxOffice": "$2.195 billion",
      "production": "20th Century Fox",
      "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/Titanic.jpg"
    },
    {
      "id": 14,
      "title": "Star Wars",
      "year": 1977,
      "genre": ["Action", "Adventure", "Sci-Fi"],
      "rating": 8.6,
      "director": "George Lucas",
      "actors": ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
      "plot": "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire's world-destroying battle station while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
      "poster": "Star_Wars",
      "trailer": "StarWars",
      "runtime": 121,
      "awards": "Won 6 Oscars",
      "country": "USA",
      "language": "English",
      "boxOffice": "$775.4 million",
      "production": "Lucasfilm",
      "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/Star+Wars+Episode+IV.jpg"
    },
    {
      "id": 15,
      "title": "The Departed",
      "year": 2006,
      "genre": ["Crime", "Drama", "Thriller"],
      "rating": 8.5,
      "director": "Martin Scorsese",
      "actors": ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"],
      "plot": "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
      "poster": "The_Departed",
      "trailer": "TheDeparted",
      "runtime": 151,
      "awards": "Won 4 Oscars",
      "country": "USA",
      "language": "English",
      "boxOffice": "$291.5 million",
      "production": "Warner Bros.",
      "image_link": "https://handson-x-learn.s3.ap-south-1.amazonaws.com/MERN_SB_GP_Images/movie-ott-images/The+Departed.jpg"
    },
    {
      "id": 16,
      "title": "Romeo + Juliet",
      "year": 1996,
      "genre": ["Drama", "Romance"],
      "rating": 6.7,
      "director": "Baz Luhrmann",
      "actors": ["Leonardo DiCaprio", "Claire Danes", "John Leguizamo"],
      "plot": "Shakespeare's famous play is updated to the hip modern suburb of Verona still retaining its original dialogue.",
      "poster": "Romeo_and_Juliet",
      "trailer": "RomeoAndJulet",
      "runtime": 120,
      "awards": "Nominated for 1 Oscar",
      "country": "USA",
      "language": "English",
      "boxOffice": "$147.6 million",
      "production": "20th Century Fox",
      "image_link": "./src/assets/RomeoAndJulet.jpg"
    }
]